jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter
        run: |
          . venv/bin/activate
          make lint
      - name: Run non-integration tests
        if: github.event.inputs.run_non_integration_tests == 'true'
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          . venv/bin/activate
          pytest -m "not integration" tests/
      - name: Run integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          . venv/bin/activate
          pytest -m "integration" tests/
      - name: Show logs on failure
        if: failure()
        run: |
          cat logs/*.log || true

