name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Check Node Version
      run: node -v

    - name: Set up environment
      run: |
        python -m venv env
        source env/bin/activate
        echo "Environment setup complete."

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        source env/bin/activate
        pylint text_processing.py

    - name: Run tests
      run: |
        source env/bin/activate
        pytest
