name: Python application

on: [push, pull_request]

jobs:
  build:
<<<<<<< HEAD
=======

>>>>>>> origin/tokenizer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
<<<<<<< HEAD

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

=======
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
>>>>>>> origin/tokenizer
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
<<<<<<< HEAD

=======
>>>>>>> origin/tokenizer
    - name: Lint with pylint
      run: |
        source env/bin/activate
        pylint text_processing.py
<<<<<<< HEAD

=======
>>>>>>> origin/tokenizer
    - name: Test with pytest
      run: |
        source env/bin/activate
        pytest

